Feature/schema
SCSummer2022/backend pull request #8
Opened 2022-07-06 16:53 UTC by QuietPhantom

Правки реквизитов

2022-07-08 14:22 UTC, HorryMode commented
Suggested edit:
```diff
diff --git a/api/user.js b/api/user.js
index 3f67d56..9015621 100644
--- a/api/user.js
+++ b/api/user.js
@@ -4,54 +4,20 @@ let router = express.Router();
 let service = require('../service/user');
 const {Learner} = require("../model/user");
 
-//todo нужно использовать тело запроса - где находятся параметры поиска
-//это page и pageSize
 let learnersSearch = async function (req, res) {
-    let learnersInfo = await service.getLearnersInfo();
+    let pageParams = req.query;
+    let learnersInfo = await service.getLearnersInfo(pageParams);
     res.json(learnersInfo)
 }
 
-
-//todo нужно использовать тело запроса - где находятся параметры поиска
-//это page и pageSize
 let teachersSearch = async function (req, res) {
     let teachersInfo = await service.getTeachersInfo();
     res.json(teachersInfo)
 }
 
-//todo использовать данные учителя из тела запроса
-let createLearner = async function (req, res) {
-    let newLearner = {
-        role_id: 1,
-        last_name: 'Кошкин',
-        first_name: 'Дмитрий',
-        second_name: 'Александрович',
-        birthday: new Date(2002, 6, 20),
-        phone_number: null,
-        email: 'demon@mail.ru',
-        password: 'YESYESYES',
-        city: 1,
-        school: 1,
-        class: 5,
-        fav_sport_types: null
-    }
-    let learnerInfo = await service.createNewLearner(newLearner);
-    res.json(learnerInfo)
-}
-
-//todo использовать идентификатор из параметра запроса
-let deleteLearner = async function (req, res) {
-    //todo убрать, так как контроллер не должен содержать бизнес логики и знать об инфраструктуре
-    let learnerForDelete = Learner.findByPk(2)
-    let learnerInfo = await service.deleteLearner(2);
-    res.json(learnerInfo)
-}
-
 
 
 router.post('/learners/search', learnersSearch)
 router.post('/teachers/search', teachersSearch)
-router.post('/learners', createLearner)
-router.post('/learners/delete', deleteLearner)
 
 module.exports = router;
\ No newline at end of file
diff --git a/model/user.js b/model/user.js
index 9ebefbc..3a49149 100644
--- a/model/user.js
+++ b/model/user.js
@@ -53,44 +53,44 @@ const Team = sequelize.sequelize.define('Team', {
 
 
 
-//СВЯЗИ ТАБЛИЦ
-/////////////////////
-//Role, Teacher
-Role.hasMany(Teacher, {foreignKey: {name: 'role_id'}})
-Teacher.belongsTo(Role, {foreignKey: {name: 'id'}})
-//Role, Learner
-Role.hasMany(Learner, {foreignKey: {name: 'role_id'}})
-Learner.belongsTo(Role, {foreignKey: {name: 'id'}})
-//Learner, Match -> MatchParticipant
-Learner.belongsToMany(tournament.Match, {through: tournament.MatchParticipant, sourceKey: 'id', targetKey: 'id'})
-tournament.Match.belongsToMany(Learner, {through: tournament.MatchParticipant, sourceKey: 'id', targetKey: 'id'})
-//Learner, Tournament -> TournamentParticipant
-Learner.belongsToMany(tournament.Tournament, {through: tournament.TournamentParticipant, sourceKey: 'id', targetKey: 'id'})
-tournament.Tournament.belongsToMany(Learner, {through: tournament.Tournament, sourceKey: 'id', targetKey: 'id'})
-//Sport_type, Learner -> connecting table
-Learner.belongsToMany(tournament.SportType, {through: 'fav_sport_type', sourceKey: 'id', targetKey: 'id'})
-tournament.SportType.belongsToMany(Learner, {through: 'fav_sport_type', sourceKey: 'id', targetKey: 'id'})
-//School, Teacher -> connecting table
-Teacher.belongsToMany(School, {through: 'Teachers_school', sourceKey: 'id', targetKey: 'id'})
-School.belongsToMany(Teacher, {through: 'Teachers_school', sourceKey: 'id', targetKey: 'id'})
-//Tournament, City -> CityParticipant
-tournament.Tournament.belongsToMany(tournament.City, {through: tournament.CityParticipant, sourceKey: 'id', targetKey: 'id'})
-tournament.City.belongsToMany(tournament.Tournament, {through: tournament.CityParticipant, sourceKey: 'id', targetKey: 'id'})
-//Tournament, Match
-tournament.Tournament.hasMany(tournament.Match, {foreignKey: {name: 'tournament_id'}})
-tournament.Match.belongsTo(tournament.Tournament, {foreignKey: {name: 'tournament_id'}})
-//Tournament, TournamentType
-tournament.TournamentType.hasMany(tournament.Tournament, {foreignKey: {name: 'tournament_type_id'}})
-tournament.Tournament.belongsTo(tournament.TournamentType, {foreignKey: {name: 'id'}})
-//Tournament, SportType
-tournament.SportType.hasMany(tournament.Tournament, {foreignKey: {name: 'sport_id'}})
-tournament.Tournament.belongsTo(tournament.SportType, {foreignKey: {name: 'id'}})
-//Learner, School
-School.hasMany(Learner, {foreignKey: {name: 'school'}})
-Learner.belongsTo(School, {foreignKey: {name: 'id'}})
-//Learner, City
-tournament.City.hasMany(Learner, {foreignKey: {name: 'city'}})
-Learner.belongsTo(tournament.City, {foreignKey: {name: 'id'}})
+// //СВЯЗИ ТАБЛИЦ
+// /////////////////////
+// //Role, Teacher
+// Role.hasMany(Teacher, {foreignKey: {name: 'role_id'}})
+// Teacher.belongsTo(Role, {foreignKey: {name: 'id'}})
+// //Role, Learner
+// Role.hasMany(Learner, {foreignKey: {name: 'role_id'}})
+// Learner.belongsTo(Role, {foreignKey: {name: 'id'}})
+// //Learner, Match -> MatchParticipant
+// Learner.belongsToMany(tournament.Match, {through: tournament.MatchParticipant, sourceKey: 'id', targetKey: 'id'})
+// tournament.Match.belongsToMany(Learner, {through: tournament.MatchParticipant, sourceKey: 'id', targetKey: 'id'})
+// //Learner, Tournament -> TournamentParticipant
+// Learner.belongsToMany(tournament.Tournament, {through: tournament.TournamentParticipant, sourceKey: 'id', targetKey: 'id'})
+// tournament.Tournament.belongsToMany(Learner, {through: tournament.Tournament, sourceKey: 'id', targetKey: 'id'})
+// //Sport_type, Learner -> connecting table
+// Learner.belongsToMany(tournament.SportType, {through: 'fav_sport_type', sourceKey: 'id', targetKey: 'id'})
+// tournament.SportType.belongsToMany(Learner, {through: 'fav_sport_type', sourceKey: 'id', targetKey: 'id'})
+// //School, Teacher -> connecting table
+// Teacher.belongsToMany(School, {through: 'Teachers_school', sourceKey: 'id', targetKey: 'id'})
+// School.belongsToMany(Teacher, {through: 'Teachers_school', sourceKey: 'id', targetKey: 'id'})
+// //Tournament, City -> CityParticipant
+// tournament.Tournament.belongsToMany(tournament.City, {through: tournament.CityParticipant, sourceKey: 'id', targetKey: 'id'})
+// tournament.City.belongsToMany(tournament.Tournament, {through: tournament.CityParticipant, sourceKey: 'id', targetKey: 'id'})
+// //Tournament, Match
+// tournament.Tournament.hasMany(tournament.Match, {foreignKey: {name: 'tournament_id'}})
+// tournament.Match.belongsTo(tournament.Tournament, {foreignKey: {name: 'tournament_id'}})
+// //Tournament, TournamentType
+// tournament.TournamentType.hasMany(tournament.Tournament, {foreignKey: {name: 'tournament_type_id'}})
+// tournament.Tournament.belongsTo(tournament.TournamentType, {foreignKey: {name: 'id'}})
+// //Tournament, SportType
+// tournament.SportType.hasMany(tournament.Tournament, {foreignKey: {name: 'sport_id'}})
+// tournament.Tournament.belongsTo(tournament.SportType, {foreignKey: {name: 'id'}})
+// //Learner, School
+// School.hasMany(Learner, {foreignKey: {name: 'school'}})
+// Learner.belongsTo(School, {foreignKey: {name: 'id'}})
+// //Learner, City
+// tournament.City.hasMany(Learner, {foreignKey: {name: 'city'}})
+// Learner.belongsTo(tournament.City, {foreignKey: {name: 'id'}})
 
 
 //NOT WORKING!!!
diff --git a/service/user.js b/service/user.js
index 4426d71..17f895a 100644
--- a/service/user.js
+++ b/service/user.js
@@ -4,25 +4,15 @@ const {Teacher} = require("../model/user");
 module.exports = {
 
 //todo нужно использовать тело запроса - где находятся параметры поиска
-    getLearnersInfo: async function (filter) {
-        let page = filter.page
-        let pageSize = filter.pageSize
+    getLearnersInfo: async function (pageParams) {
+        let page = pageParams.page;
+        let pageSize = pageParams.pageSize;
         await require('../model/user-data').init();
-        return Learner.findAll();
+        return  [...]

2022-07-11 08:04 UTC, andrew--i requested changes

2022-07-11 08:04 UTC, andrew--i commented on service/match.js
> +    let AllMatches = await Match.findAll({
Возможно можно передать параметры постраничности в запрос, чтобы не нжуно было из БД выкачивать все записи турнира ?

типа LIMIT, OFFSET какие то параметры в запросе к БД ?

2022-07-11 08:04 UTC, andrew--i commented on service/user.js
> +            let learnerInfo = await Learner.findByPk(i);
это не совсем корректно.

1. тут делается допущение, что идентификаторы идут попорядку и совпадают со страницами. но это не так. 
например, пусть есть 3 ученка с id 1,2,3 соответсвенно. если мы через api удалим ученика с id=2, то в бд остануться 1 и 3 ученики. и если мы попросим всех учеников, с page:0, pageSize:2 - то должно вернуться 2 ученика, а вернется 1. это не правильно

2. в идеале, сделать один запрос к БД. в данный момент вы делаете pageSize запросов к БД

2022-07-11 08:04 UTC, andrew--i commented on service/user.js
> +            teacherInfo = await Teacher.findByPk(i);
аналогично ученику

2022-07-11 09:37 UTC, merged